name: V1
on:
  watch:
    types: [started]
    
#  push:
#    branches: 
#      - master
  
jobs:
  timer1:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Run boot script
      run: |
        ./autoexec.sh
        
    - name: Timer
      run: |
        ./timer.sh

  timer2:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer3:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer4:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer5:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer6:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer7:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer8:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer9:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer10:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer11:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh

  timer12:
    runs-on: ubuntu-18.04
    steps:
    - name: Timer
      run: |
        ./timer.sh
