name: V1
on:
  watch:
    types: [started]
    
#  push:
#    branches: 
#      - master
  
jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 4300
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Run boot script
      run: |
        ./autoexec.sh
        
    - name: Timer
      timeout-minutes: 4300
      run: |
        ./timer.sh
        
  
